<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [Failed suite [Failed suite [Suite]]]" duration-ms="63" started-at="2023-03-28T01:11:52Z" finished-at="2023-03-28T01:11:52Z">
    <groups>
    </groups>
    <test name="Test(failed)(failed)(failed)" duration-ms="63" started-at="2023-03-28T01:11:52Z" finished-at="2023-03-28T01:11:52Z">
      <class name="com.project.extra.SearchProductTest">
        <test-method status="FAIL" signature="searchSpecificProductTest()[pri:0, instance:com.project.extra.SearchProductTest@490ab905]" name="searchSpecificProductTest" duration-ms="32" started-at="2023-03-28T01:11:52Z" finished-at="2023-03-28T01:11:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Some reason]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Some reason
at org.testng.Assert.fail(Assert.java:96)
at com.project.extra.SearchProductTest.searchSpecificProductTest(SearchProductTest.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchSpecificProductTest -->
      </class> <!-- com.project.extra.SearchProductTest -->
    </test> <!-- Test(failed)(failed)(failed) -->
  </suite> <!-- Failed suite [Failed suite [Failed suite [Suite]]] -->
</testng-results>
